sudo: required
language: python
cache: pip

python:
    - 3.5

services:
    - docker

before_install:
    - docker build -t cocotb-image cocotb/
    - docker run --name n2t -d -v $PWD:/nand2tetris cocotb-image sleep infinity

script:
    - docker exec n2t /bin/bash -c "cd /nand2tetris && make"
